update azuredeploy json
bcgov/jag-instrumentation pull request #6
Opened 2020-03-09 15:06 UTC by rantifamilusi

azure deploy json for splunk server in cloud

2020-03-10 16:23 UTC, poggdogg requested changes
Minor stuff, just missing some newlines

2020-03-10 16:23 UTC, poggdogg commented on Splunk/ecm/configs/iis-add-on-inputs.conf
> +sourcetype = ms:iis:auto
Add this newline

2020-03-10 16:23 UTC, poggdogg commented on Splunk/ecm/script/perfmon_extract.py
> +create_file(extract_perfmon(30))
newline here too

2020-03-10 16:23 UTC, poggdogg commented on Splunk/ecm/splunk-lab/azuredeploy.json
> +  }
newline here

2020-03-10 16:23 UTC, poggdogg commented on Splunk/ecm/splunk-lab/azuredeploy.json
> +  }
Cool that we got a template.  Keep in mind that their containers can be more expensive than VMs because they are up in multiple AZs

2020-03-12 22:08 UTC, poggdogg approved these changes

2020-03-12 23:26 UTC, emuthiah commented
Looks good to me.

2020-03-12 23:27 UTC, merged